repos:
  - repo: meta
    hooks:
      - id: identity
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: helmlint
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.10.0
    hooks:
      - id: pretty-format-yaml
        args:
          - --autofix
          - --preserve-quotes
          - --indent
          - "2"
          - --offset
          - "2"
        exclude: ^charts/
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.1
    hooks:
      - id: helm-docs
