apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-helm-charts.fullname" . }}
  labels: {{- include "home-helm-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "home-helm-charts.selectorLabels" . | nindent 6 }}
  {{- with .Values.rolloutStrategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:  {{- include "home-helm-charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "home-helm-charts.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
        {{- with .Values.env }}
        env:
        {{- range $k, $v := . }}
        - name: "{{ $k }}"
          value: "{{ $v }}"
        {{- end }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.startupProbe }}
        startupProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeMounts }}
        volumeMounts: {{- toYaml . | nindent 8 }}
        {{- end }}
      hostNetwork: {{ default false .Values.hostNetwork }}
      {{- with .Values.volumes }}
      volumes: {{- toYaml . | nindent 6 }}
      {{- end }}
