{{- if (.Values.service).enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-helm-charts.fullname" . }}
  labels: {{- include "home-helm-charts.labels" . | nindent 4 }}
spec:
  type: {{ (.Values.service).type }}
  ports:
    {{- if (.Values.service).ports }}
    {{- toYaml (.Values.service).ports | nindent 4 }}
    {{- else }}
    - name: http
      protocol: TCP
      port: {{ (.Values.service).port }}
      targetPort: {{ default (.Values.service).port (.Values.service).targetPort }}
      {{- if (.Values.service).nodePort }}
      nodePort: {{ default "" (.Values.service).nodePort }}
      {{- end }}
    {{- end }}
  selector: {{- include "home-helm-charts.selectorLabels" . | nindent 4 }}
{{- end }}
