{{- if (.Values.ingress).enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "home-helm-charts.fullname" . }}
  labels: {{- include "home-helm-charts.labels" . | nindent 4 }}
  {{- with (.Values.ingress).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with (.Values.ingress).hosts }}
  rules: {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with (.Values.ingress).tls }}
  tls: {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
